// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/aliskhannn/delayed-notifier/internal/model"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	retry "github.com/wb-go/wbf/retry"
)

// MocknotificationService is a mock of notificationService interface.
type MocknotificationService struct {
	ctrl     *gomock.Controller
	recorder *MocknotificationServiceMockRecorder
}

// MocknotificationServiceMockRecorder is the mock recorder for MocknotificationService.
type MocknotificationServiceMockRecorder struct {
	mock *MocknotificationService
}

// NewMocknotificationService creates a new mock instance.
func NewMocknotificationService(ctrl *gomock.Controller) *MocknotificationService {
	mock := &MocknotificationService{ctrl: ctrl}
	mock.recorder = &MocknotificationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknotificationService) EXPECT() *MocknotificationServiceMockRecorder {
	return m.recorder
}

// CreateNotification mocks base method.
func (m *MocknotificationService) CreateNotification(arg0 context.Context, arg1 retry.Strategy, arg2 model.Notification) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNotification", arg0, arg1, arg2)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNotification indicates an expected call of CreateNotification.
func (mr *MocknotificationServiceMockRecorder) CreateNotification(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNotification", reflect.TypeOf((*MocknotificationService)(nil).CreateNotification), arg0, arg1, arg2)
}

// GetAllNotifications mocks base method.
func (m *MocknotificationService) GetAllNotifications(arg0 context.Context) ([]model.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllNotifications", arg0)
	ret0, _ := ret[0].([]model.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllNotifications indicates an expected call of GetAllNotifications.
func (mr *MocknotificationServiceMockRecorder) GetAllNotifications(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllNotifications", reflect.TypeOf((*MocknotificationService)(nil).GetAllNotifications), arg0)
}

// GetNotificationStatusByID mocks base method.
func (m *MocknotificationService) GetNotificationStatusByID(arg0 context.Context, arg1 retry.Strategy, arg2 uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotificationStatusByID", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotificationStatusByID indicates an expected call of GetNotificationStatusByID.
func (mr *MocknotificationServiceMockRecorder) GetNotificationStatusByID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotificationStatusByID", reflect.TypeOf((*MocknotificationService)(nil).GetNotificationStatusByID), arg0, arg1, arg2)
}

// SetStatus mocks base method.
func (m *MocknotificationService) SetStatus(ctx context.Context, strategy retry.Strategy, id uuid.UUID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatus", ctx, strategy, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MocknotificationServiceMockRecorder) SetStatus(ctx, strategy, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MocknotificationService)(nil).SetStatus), ctx, strategy, id, status)
}
